/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./sections/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-surface-variant": "#adaaaa",
        "on-secondary-fixed": "#41009a",
        "on-tertiary-fixed-variant": "#001ab6",
        "on-primary-container": "#005359",
        "tertiary-dim": "#4f62ff",
        "error": "#ff716c",
        "surface-container-lowest": "#000000",
        "secondary-fixed": "#dac9ff",
        "primary-fixed-dim": "#00deec",
        "surface-container-highest": "#262626",
        "surface-container-low": "#131313",
        "on-secondary-container": "#f8f1ff",
        "outline": "#777575",
        "on-secondary": "#290067",
        "tertiary-fixed-dim": "#909bff",
        "secondary-fixed-dim": "#ceb9ff",
        "on-error-container": "#ffa8a3",
        "surface-dim": "#0e0e0e",
        "outline-variant": "#494847",
        "surface-container": "#1a1919",
        "surface-variant": "#262626",
        "surface-tint": "#8ff5ff",
        "error-container": "#9f0519",
        "tertiary": "#8995ff",
        "primary-fixed": "#00eefc",
        "error-dim": "#d7383b",
        "on-primary": "#005d63",
        "on-tertiary-container": "#e5e5ff",
        "primary": "#8ff5ff",
        "on-surface": "#ffffff",
        "inverse-primary": "#006a71",
        "primary-container": "#00eefc",
        "surface": "#0e0e0e",
        "on-error": "#490006",
        "background": "#0e0e0e",
        "secondary-container": "#7000ff",
        "on-tertiary": "#000c70",
        "surface-bright": "#2c2c2c",
        "on-secondary-fixed-variant": "#6300e2",
        "secondary-dim": "#874cff",
        "on-background": "#ffffff",
        "inverse-surface": "#fcf8f8",
        "tertiary-container": "#052bff",
        "primary-dim": "#00deec",
        "surface-container-high": "#201f1f",
        "secondary": "#ac89ff",
        "on-primary-fixed-variant": "#005e64",
        "tertiary-fixed": "#a1aaff",
        "on-primary-fixed": "#003f43",
        "on-tertiary-fixed": "#00085a",
        "inverse-on-surface": "#565554"
      },
      fontFamily: {
        "headline": ["var(--font-space-grotesk)"],
        "body": ["var(--font-inter)"],
        "label": ["var(--font-space-grotesk)"]
      },
      borderRadius: {"DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem"},
      animation: {
        beam: "beam 4s infinite linear",
      },
      keyframes: {
        beam: {
          "0%": { transform: "translateX(-100%) translateY(0)", opacity: 0 },
          "50%": { opacity: 1 },
          "100%": { transform: "translateX(200%) translateY(0)", opacity: 0 },
        },
      },
    },
  },
  plugins: [require("@tailwindcss/forms")],
}
